version: '3.7'
services:
  helix-honeypot-k8s:
    build: ./
    ports:
      - "127.0.0.1:8111:8111"
    volumes:
      - k8s_log:/var/log
    environment:
      - RUN_MODE=k8s
      - HELIX_LOCATION=testing
      - K8SAPI_VERSION=v1.21
      - IP_BASE=192.168
      - GENERATE_KUBE_SYSTEM=true
      - GENERATE_RANDOMNESS=true
      - K8S_HOST=0.0.0.0
      - K8S_PORT=8111

  helix-honeypot-http:
    build: ./
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - http_log:/var/log
    environment:
      - RUN_MODE=http
      - HELIX_HTTP_HOST=0.0.0.0
      - HELIX_HTTP_PORT=8000

  helix-honeypot-tcp:
    build: ./
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - tcp_log:/var/log
    environment:
      - RUN_MODE=tcp
      - HELIX_TCP_HOST=0.0.0.0
      - HELIX_TCP_PORT=3000

  helix-honeypot-udp:
    build: ./
    ports:
      - "127.0.0.1:53535:53/udp"
    volumes:
      - udp_log:/var/log
    environment:
      - RUN_MODE=udp
      - HELIX_UDP_HOST=0.0.0.0
      - HELIX_UDP_PORT=53

  helix-honeypot-def:
    build: ./
    ports:
      - "127.0.0.1:8001:8001"
    volumes:
      - def_log:/var/log
    environment:
      - RUN_MODE=def
      - HELIX_DEF_HOST=0.0.0.0
      - HELIX_DEF_PORT=8001

volumes:
  k8s_log:
    driver: local
  http_log:
    driver: local
  tcp_log:
    driver: local
  udp_log:
    driver: local
  def_log:
    driver: local